### ISSUE TITLE
csgosl not detecting server install

### ISSUE THREAD

**Issue by Z0W** [lenosisnickerboa/csgosl#112]
After I csgosl downloads the server and stuff. I restart and the prompt pops up that says "no installed server was detected".
Tried on two different machines running windows 10.

**Comment by lenosisnickerboa** [comment]
Check if file <your-install-folder>/server/srcds.exe exists. That is the only check csgosl does to determine if a server is installed. 

Other things to consider:
- Do yu see any error messages during server install? Check console windows during and after install.
- avoid spaces in installation path
- check available disk space (since you've tried on two different machines this is not a likely cause...)

**Comment by Z0W** [comment]
Yeah, /server/srcds.exe isn't in the folder. But I don't see any errors in console output.

**Comment by Z0W** [comment]
Was a disk space problem.. Thanks for the help
