### ISSUE TITLE
Cannot connect after initially joining

### ISSUE THREAD

**Issue by tig8** [lenosisnickerboa/csgosl#116]
Lenosis -

Having two issues with the csgosl. After following the installation instructions the server successfully creates. However when I join I cannot move at all and the server soon after crashes (if i add allmaps to the map list the sever doesn't crash but continuously calls for a new map vote after ~30 seconds) 

The second issue is (I dont believe this is specific to csgosl) after I leave the server and try to rejoin, I get a connection failed. When i go back to the cmd/csgosl to see whats up I see the srcds.exe crashes. The cmd mentioned a cookie reservation of 0 and the server then shuts down.  

Your help would be greatly appreciated.

**Comment by tig8** [comment]
Now the server seems to be staying online (able to rejoin), but the problem of being frozen in the server and a continuous map vote still exists.

**Comment by spacecow123** [comment]
I actually have this same issue with both of my servers, I think it has to do with sourcemod updating. Everyn time I update the server I need to join it once to make sourcemod update/server then crashes. Restart the server then join again and its ok.

**Comment by tig8** [comment]
Yeah I just tried again and the server crashed once i joined (srcds.exe crashes on back end). Also still frozen in server and continuous map vote

**Comment by tig8** [comment]
@lenosisnickerboa After a lot of digging it seems running the game as competitive solved the "frozen in server problem". Not sure why...

In terms of srcds.exe stopped working its due to a "Missing shutdown function for Sys_InitAuthentication() : Sys_ShutdownAuthentication()" It has something to do with changing maps or the map the server is loaded with... Any thoughts are appreciated

**Comment by lenosisnickerboa** [comment]
Not sure what's going on, sounds like csgosl is not involved, but you never know...

You talk about map changes, have you tried creating a new mapgroup, e.g. maps1, and and a single preinstalled map, e.g. ar_baggage, to it and then start the server with mapgroup set to maps1 and startmap set to ar_baggage and connect. Do you still see the same problems? Or are the problems related to loading of a new map, perhaps some downloaded workshop map?

**Comment by tig8** [comment]
Thanks for the timely response @lenosisnickerboa 

I have to think its semi related to csgosl because I tested with multiple users and the problem remained the same. Anyway, I sort of did what you said by editing the allmaps group to only 4 known maps (d2,mirage, inferno, cache). This keeps the server running in terms of being able to rejoin once everyone leaves but yesterday once I completed a "competitive" match on dust2 and the mapvote kicked in the server crashed when switching maps. Again getting the Missing shutdown function for Sys_InitAuthentication() : Sys_ShutdownAuthentication() in the cmd causing srcds.exe to stop working.

**Comment by lenosisnickerboa** [comment]
Don't understand your initial comment "_I have to think its semi related to csgosl because I tested with multiple users and the problem remained the same._" and how this makes it more of a csgosl related problem? It seems a lot of people sometimes run into the problem but I see no clear and obvious solution.

Do you have sourcemod enabled? If yes, try disabling it. Googled "Sys_InitAuthentication" and found a lot of sourcemod related issues. This is just to rule out sourcemod. csgosl uses the latest stable sourcemod version 1.8.0-6040.

Also found this post suggesting a csgo server bug and that the startmap is part of the problem:

`This is part of CSGO's retarded server logicSourceMod doesn't matter at allCSGO doesn't like SourceMod or server editingIt ALWAYS occur without any reason.For me, changing to a map called zm_parish_b2 will result 50% chanace of that problem.I highly recommend you to change the first launching map in the command line.There is no way to kill it permanentlyHidden Path had done a REALLY good job on srcds`

[Comment from here](https://forums.alliedmods.net/showthread.php?t=239469)

Maybe try changing startmap?

**Comment by tig8** [comment]
I have it so the server starts with dust2, cache, mirage or inferno so start map is not the issue. Its after a match is completed and the server executes the automatic map vote. Once the server tries changing the map the server crashes.

**Comment by lenosisnickerboa** [comment]
Any news on this? I don't have any clue what to do about it?

**Comment by lenosisnickerboa** [comment]
Closing, not getting anywhere. Please reopen if you want.
