### ISSUE TITLE
Clean version

### ISSUE THREAD

**Issue by gilobij** [lenosisnickerboa/csgosl#226]
Hi, can you make clean csgosl, without any configs or addons. Like SteamCMD.GUI provide? I just want download csgo install sourcemod and my plugins? Im asking this because, seems like I have confilicts with installed metamod and sourcemod folder contents and CSGOSL overwrite always these folders.

**Comment by gilobij** [comment]
Also seems like your program change addon cvars in startup. Any fix of this?

I use this addon https://forums.alliedmods.net/showthread.php?t=233685

**Comment by lenosisnickerboa** [comment]
That kind of defeats the csgosl purpose, to provide a simple click-and-run experience for inexperienced users. As I see it you can instead use csgosl to just install an initial version for you and then manage everything yourself, editing config files and manage sourcemod plugins, and so on... 
csgosl csgosl will place two bat-files/scripts cmd-start.bat/.sh and cmd-update.bat/.sh in csgosl/bin. The first will contain the complete command to start your server and the second the command to update the server. Using these two scripts instead of starting csgosl will prevent csgosl from overwriting your stuff and also provides handy shortcuts for starting and updating your server. You will have to maintain sourcemod/metamod updates yourself though.
Not exactly what you want but perhaps a middle ground?

**Comment by gilobij** [comment]
Thanks for help! Can you help me with bots? https://forums.alliedmods.net/showthread.php?p=2672589#post2672589

**Comment by lenosisnickerboa** [comment]
Sorry, haven't used these plugins so no clue.
