### ISSUE TITLE
Server not detected

### ISSUE THREAD

**Issue by peto2006** [lenosisnickerboa/csgosl#228]
After installing server using `csgosl` and restarting `csgosl`, I get warning that "_No installed server was detected_..."

* File `server/srcds.exe` does not exist. [Here](https://pastebin.com/raw/M0RupeJw) is full list of files.
* I have more than 50GB free space on particular HDD.
* I didn't see any errors, but console closes after install so it would be difficult to see any.
* Using Windows 10 (1903). Csgosl v2.7.7.

**Comment by lenosisnickerboa** [comment]
The only thing I can come up with the installation was interrupted for some reason, since the srcds.exe file is not present. There may be some logs in the csgosl\steamcmd\logs folder? Have you checked? Look for the ones with timestamps close to installation time.
Other than that, I would remove the installation folder and try again.

**Comment by peto2006** [comment]
It's my fault. I don't use Windows often, I forgot that my desktop is stored on ssd, with less free space. Sorry for wasting your time and thank you for pointing me to logs.

**Comment by lenosisnickerboa** [comment]
No worries! Hope everything worked out for you!
