### ISSUE TITLE
server doesn't start

### ISSUE THREAD

**Issue by switch2323** [lenosisnickerboa/csgosl#256]
First of all, thanks for this nice tool!

Unfortunately few days ago, maybe because of the new version (but i tried 2.8.0 and same thing), maybe because of windows update, or update of my Motherboard and bios, or...
when i click on start server -> nothing is happening. I put all to default but still nothing.

I tried to create another bat file to start manually server and it doesn't work. (maybe i'm doing it wrong)

Thanks for your help

csgosl version: 2.8.1 (same 2.8.0)
platform: windows 10
describe problem: server doesnt start (no cmd window)
does it happen every time or just once-in-a-while: every time, impossible de start
did this work before and stopped working: start maybe on windows update or update of bios and drivers Motherboard card
if it stopped working, what changed? updated csgosl? updated csgo server? Updated csgosl, maybe server too (it's automatic when i start Csgosl), windows, drivers, ...
screen dump: /
console output: /

**Comment by lenosisnickerboa** [comment]
Hmmm... strange. Seems like you did a lot of changes all at once. Do you have sourcemod enabled? Try disabling that first just to get that out of the way. Actually updated the "report a bug" page with some sourcemod related stuff since sourcemod is often an issue when you get server problems.
See updated https://github.com/lenosisnickerboa/csgosl/wiki/Report-a-bug

**Comment by switch2323** [comment]
Thanks to answer me.
I disabled sourcemod -> same thing : nothing happen when i click on start.
And now, when i start Csgosl, no automatic update check. I have to do it manually.

Is it possible that somehow, Windows doesnt allow to open CMD windows, and launch server?

csgosl version: 2.8.1 (same 2.8.0)
platform: windows 10
describe problem: server doesnt start (no cmd window)
does it happen every time or just once-in-a-while: every time, impossible to start
did this work before and stopped working: start maybe on windows update or update of bios and drivers Motherboard card
if it stopped working, what changed? updated csgosl? updated csgo server? Updated csgosl, maybe server too (it's automatic when i start Csgosl), windows, drivers, ...
screen dump: /
console output: /

**Comment by lenosisnickerboa** [comment]
"Is it possible that somehow, Windows doesnt allow to open CMD windows, and launch server?"
Really have no idea. Haven't had any issue like this reported before. 

Some wild guesses:
- could C: be full or nearly full? some weird problems have been reported when people run csgosl on a full disk.
- some people (not all) have problems when csgosl is installed in a folder which has spaces in it. Try to move your entire folder "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgosl" to e.g.  "C:\csgosl" instead and try starting csgosl from there instead.

**Comment by switch2323** [comment]
C: is still 9 Gb free left.
I moved it to C:\csgosl --> nothing changed

I copied Csgosl to a D: with plenty of free GB and during 1 second when i click on START server, i saw the button STOP server than it went back to START. No server window. nothing happen when i click on Start now

**Comment by lenosisnickerboa** [comment]
Try this to perhaps get some more information about what happens. You can have csgosl open during this test.
Open a command prompt (WIN->R cmd + enter) and type the following:
C: <press enter>
cd csgosl\bin <press enter>
cmd-start.bat <press enter>

See if you get any error messages or if the server starts. Observe the csgosl UI to see if the "Start server" text changes to "Stop server"

This is what this looks like for me (I have csgosl installed in another location at F:):

![image](https://user-images.githubusercontent.com/16888566/80122052-53bd0180-858d-11ea-8261-b67caa611e98.png)

I didn't show the whole terminal since it contains some personal info as well. A new terminal window should open and the server should start in that window.

**Comment by switch2323** [comment]
when i write this "cd csgosl\bin"
error is : the specified pass is not found

**Comment by lenosisnickerboa** [comment]
Try:
dir
cd csgosl
dir
cd bin

dir will show if csgosl and bin exists

**Comment by switch2323** [comment]
I'm doing it wrong maybe...
i have to write "dir" than Enter? than write "cd csgosl" than Enter?

**Comment by lenosisnickerboa** [comment]
Yup, the command dir list the folders in the current folder. cd takes you
into the folder you state. So, dir will show you if the folder exists
before going into it.

**Comment by switch2323** [comment]
dir ---> 
"the volume in dick C doesn't has name" The serial  number is ....

Than it lists some folders but no Csgosl in it

cd csgosl---> the path is not found...

i think i have to reinstall it all...?

**Comment by lenosisnickerboa** [comment]
Yup, try to reinstall to e.g. c:\csgosl

**Comment by switch2323** [comment]
Thanks for your help, 

i reinstalled all the server in D: and it wroks fine now :)

**Comment by lenosisnickerboa** [comment]
That's great to hear!
