### ISSUE TITLE
compatibility versions of active duty maps from workshop do not work

### ISSUE THREAD

**Issue by napzka** [lenosisnickerboa/csgosl#258]
I have tried to add old versions of maps that are already included with the server (e.g. pre-remake Dust II and Cobblestone) through a workshop collection, but the old versions do not show up in the map selector (even after restart). In-game the most recent version just gets loaded. Other workshop maps work fine.

**Comment by napzka** [comment]
It would seem this has to do with the fact that the names of these maps' bsp files is the same as the "original".

**Comment by lenosisnickerboa** [comment]
Could you include the links to the workshop maps you've tested and I'll give it a go.

**Comment by napzka** [comment]
I can't find the version of Dust II I used but [here's the Cobblestone](https://steamcommunity.com/sharedfiles/filedetails/?id=1542127528) I used.

**Comment by lenosisnickerboa** [comment]
OK, did some map group work in https://github.com/lenosisnickerboa/csgosl/releases/tag/v2.9 and I will not fix this issue, sorry. I use the map name as key in too many places so it will be too much work redesigning stuff to cope with two maps using same map name.

Have you tried renaming the bsp file in the workshop/<id> folder and then restart csgosl? Or since v2.9 you just click the "RefreshMaps" button.
