### ISSUE TITLE
My server wont start

### ISSUE THREAD

**Issue by CJNiiva** [lenosisnickerboa/csgosl#27]
[youtube video](https://www.youtube.com/watch?v=Nu8g069xTps)

okei, so I was recording with audio, but my mic didnt work, so I'm going to use the video and type here what my issue is...

FYI: I have installed the server multiple times and tried over and over again, but it seems the issue is with the server-start.bat file or whatever its called....
 
but to the issue and how it is, I try to press the start server button, and when I do that I get transfered to the run page, no harm done (I think) and then nothing happens, so I go over to the console tab and I see the command that doesnt work (that you can see in the video) but I can start the server by removing what is in front of the normal command that the program sends, but then it crashes, so I'm not sure what I have done wrong, I dont even think I have done anything wrong, I really do want to use this program but it seems that I have to go back to the oldschool way, eventhough the oldschool way is really unpractical with all this new shit like steam api etc

**Comment by lenosisnickerboa** [comment]
Watched the clip ( :+1:  ) and I really can't see anything causing your problem so I'll start with some questions. Please bear with me if they seem very basic, I'm just trying to rule out possible causes...

- Which windows version are you running? (I have tested on windows 7 and 10, just retested fresh install using csgosl 1.1 on Windows 10 which is what it seems you're running judging from the clip)
- Have you tried installing the server, restarting csgosl and then directly select "Start Server" button without changing anything? The server should always start using default values.
- If you select the "Update Server" button, is that succesful?
- Do you have free diskspace on F:? (where the server is located according to the clip, a full or almost full disk gives weird behaviour)
- First time after install when you tried "Start Server" did you get a question from Windows firewall about allowing CSGO network access? And if so, did you allow it access?
- Has it ever worked starting the server? Even once?
- If you start csgosl from the install directory, i.e. click on csgosl.vbs directly instead of the shortcut on your desktop, does that change anything?

A final test:

Go into the directory where you installed csgosl. You should see the file csgosl.vbs in this directory. Go into directory "bin" and right-click the file server-start.bat and select Edit.

The contents should be just these two lines:
@REM echo wrapper called with %*
%*

First add a line before "%*" stating "notepad". The new contents should look like this:
@REM echo wrapper called with %*
notepad
%*

Save the file and click the "Start Server" button. **Please tell me if notepad is started or not**.

Then again edit server-start.bat and instead of notepad enter the command line you saw in the console page, the one where you had removed bin/server-start.bat in the beginning. Also comment the last line as shown in the example below (this is the command I used on my newly installed test server on Windows 10). New contents:

@REM echo wrapper called with %*
bin/server-start.bat "D:/_NB/csgosl 1.1/server/srcds"  -game csgo -console   +game_type 0 +game_mode 0  +mapgroup mg_active  +map de_dust2     -maxplayers_override 16  -tickrate 128      +hostname "Your server at lenoswd operated by csgosl PATCH" -port 27015 +sv_lan 1
@REM %*

Save the file and then click "Start Server" again and **tell me what happens**.

Let's start with this and see where it gets us.

**Comment by CJNiiva** [comment]
okei, I did a bit of testing, and got it working, but only when I had it installed on my desktop in a folder named csgosl , found this to be very wierd, probably some code that is for example C://example/example2/csgosl/andsomeotherstuff

**Comment by lenosisnickerboa** [comment]
That's indeed weird. I installed it in a completely different folder with
spaces and quotes in the name and it works right out of the box. Also moved
and renamed the folder and it still works. And it runs on linux as well.

But if you got a working installation now you should be able to move the
complete folder where ever you want and run it from there. Just update the
shortcut of course.

Which windows version are you running btw?
Den 16 maj 2016 04:33 skrev "CJNiiva" <notifications@github.com>:

**Comment by CJNiiva** [comment]
I'm running windows 10, and to be a little bit more spesific I had it installed in a megasync folder, that might have been the issue, but its still wierd:/ I'm gonna try it again in the megasync folder

**Comment by lenosisnickerboa** [comment]
Closing this issue, please reopen if you have more problems.
