### ISSUE TITLE
PNG load error Interlace handling should be turned on when using png_read_image

### ISSUE THREAD

**Issue by SuperK2-OS** [lenosisnickerboa/csgosl#279]
Hi, my friends see this message when trying to connect my server (Linux Mint 19.3).

What I´m doing wrong ?

Sorry for my english

The full error is:

PNG load error Interlace handling should be turned on when using png_read_image
Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_INGAME
** Unable to localize '#GenericConfirmText_Label' on panel descendant of 'MMStatus'
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_MAINMENU
PNG load error Interlace handling should be turned on when using png_read_image

Thanks in advance

**Comment by lenosisnickerboa** [comment]
Never seen this myself. I assume you have installed everything suggested here for Linux Mint: https://github.com/lenosisnickerboa/csgosl/wiki/Installing-a-new-server and that you don't get any error messages during installation?

Tried googling "PNG load error Interlace handling should be turned on when using png_read_image" and got a lot of results, none with a direct fix. And since I don't have the problem I can't really verify if it works.

You don't say what kind of problems your friends get? Are they unable to connect and play? Or are graphics broken? Or... ? Please describe the issue further.

**Comment by lenosisnickerboa** [comment]
No response, please reopen if still an issue.
