### ISSUE TITLE
Can't seem to change GOTV port

### ISSUE THREAD

**Issue by kENN1N** [lenosisnickerboa/csgosl#285]
![Unavngivet](https://user-images.githubusercontent.com/49256531/88856935-ac87e000-d1f5-11ea-882d-537d63736b11.png)
No matter what i do, i cant seem to change the GOTV port on the server

- I tried through the GUI
- I tried with RCON in-game
- I tried in the server config which i guess is what the GUI is editing aswell

Reason why i want it changed is because im running
4 x Match Servers with a GOTV on each

Hope someone else has figured it out! :D

**Comment by kENN1N** [comment]
Port in GUI is 27070
Upper CMD window is that server, wrote status and it says GOTV port is 27020 like the rest of the servers even tho they all have different gotv port set in the GUI

**Comment by lenosisnickerboa** [comment]
Is this a problem only when running multiple servers or do you get the same problem with just one server with a non default port setting? I would start one csgo server with GOTV port 27070 to see if that works first. From what I can see all the configs are set correctly by csgosl but maybe something has changed in GOTV since csgosl introduced GOTV support? I just set `tv_port "27070"` in the `server.cfg` file. If you look into the `server.cfg` file, does it contain the correct port value?

**Comment by kENN1N** [comment]
- The ports are correct in the server.cfg filed in server/csgo/cfg folder
- The port is still 27020 when running 1 server only even tho csgosl & server config says 27070

Looking through [https://nodecraft.com/support/games/csgo/enabling-gotv-on-your-cs-go-dedicated-server-to-spectate-and-record-your-matches](url) i see it must be set as a start parameter.

When csgosl launch the server it uses some parameters like you would do when you make it the srcds way something like " srcds -game csgo -console -usercon +game_type 0 +game_mode 1 +mapgroup mg_active +map de_dust2  " 

Can we add parameters like that? - is that what the " Misc " is for because i think the solution to change the port is to add +tv_port 27070

**Comment by lenosisnickerboa** [comment]
Well scouted 😁 !

Yes, you can try the Run tab, misc section, options setting. Everything
entered here will be appended to the command line. Please report back if
this works so I can fix csgosl to do this automatically. Also provide the
link where you found this info since there could be more options which
should entered on the command line.

**Comment by kENN1N** [comment]
Thanks!
I just tried the solution and it works ;)
![yes](https://user-images.githubusercontent.com/49256531/89306307-f9ddd480-d66f-11ea-8cc4-69d627250e20.png)

- I entered the " Run " section and under " Options " i typed in +tv_port 27070 and started the server, you can see the result on the screenshot, now the gotv port is 27070 ! 

I got the information from - https://nodecraft.com/support/games/csgo/enabling-gotv-on-your-cs-go-dedicated-server-to-spectate-and-record-your-matches

**Comment by lenosisnickerboa** [comment]
Fixed in 2.9.3. Please let me know if this fixes the problem.

**Comment by lenosisnickerboa** [comment]
No comments, closing.
