### ISSUE TITLE
Can't install server on windows 10

### ISSUE THREAD

**Issue by markojerry** [lenosisnickerboa/csgosl#290]
Hi, when i try to press the "Install server" Button it throws an error that goes like this:

```not_running
find: '/I': No such file or directory
find: 'ExecutablePath=C:\\Users\\me\\Desktop\\csgosl\\server\\srcds.exe': No such file or directory
not_running
find: '/I': No such file or directory
find: 'ExecutablePath=C:\\Users\\me\\Desktop\\csgosl\\server\\srcds.exe': No such file or directory
    while executing
"exec "$serverControlScript-status.bat""
    (procedure "DetectServerRunning" line 6)
    invoked from within
"DetectServerRunning"
    (procedure "UpdateServer" line 9)
    invoked from within
"UpdateServer"
    invoked from within
".title.update invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .title.update"
    (command bound to event)```

Any help?

**Comment by lenosisnickerboa** [comment]
This sounds like a windows PATH problem. You probably have something else installed which have modified your PATH so that it finds another "find command" before Windows own "find command" (which is what csgosl uses). See this similar problem: [similar problem](https://github.com/lenosisnickerboa/csgosl/issues/237) or more [similar problems](https://github.com/lenosisnickerboa/csgosl/issues?q=is%3Aissue+find%3A+%2FI%3A+No+such+file+or+directory)

**Comment by lenosisnickerboa** [comment]
No comments, closing.
