### ISSUE TITLE
Cannot connect to a LAN server.

### ISSUE THREAD

**Issue by kolour** [lenosisnickerboa/csgosl#291]
When I try to host a LAN server on my Windows 10 PC it does not show up in the server browser nor am I able to connect to it via my local IP address. I have tried disabled my firewall to see if that would fix it but no, it did not.

**Comment by lenosisnickerboa** [comment]
You mean you can't connect to it even from the same Windows machine you're running csgosl on?
When you connected via IP address did you specify port as well? e.g. 192.168.1.123:27015  (27015 is the default port and 192.168.1.123 is an example local IP address)

**Comment by kolour** [comment]
Yes, I am trying to connect to my own PC with a specified port.

**Comment by lenosisnickerboa** [comment]
I guess you're using the Favorites tab in csgo to connect since the Lan tab doesn't show your server. I have sometimes noticed my server doesn't show up in the Lan tab but it usually does, at least after having refreshed a few times. I have also added the server in the Favorites tab but I don't know if that affects the way it is found in the Lan tab.

Do you use the local IP address when trying to connect? Or the computer name? Try using the ip address if the name fails. The local IP address is shown in the csgosl window title afte*
Do you have multiple network interfaces/network cards? Try typing ifconfig in command prompt and see if you get multiple responses. Could be e.g. ethernet, wifi, vpns, ... connections. If you have multiple interfaces you could try disabling wifi, disable VPN... or try to connect to the different IP addresses in csgo.

Other than that I can't really come up with anything. It usually just works if you have a standard Windows machine with one network card and the Windows firewall.

**Comment by lenosisnickerboa** [comment]
No comments, closing.
