### ISSUE TITLE
lanonly setting is not worked

### ISSUE THREAD

**Issue by usgitAz** [lenosisnickerboa/csgosl#339]
hi 
i try to make public  csgo server and I did the port forwarding and i sure the lanonly setting is not ticked on server tab .
but its not worked !
in cmd-start.bat  sv_lan == 1
in server.cfg  =  lanonly "0"
eror in game when try to connect whit public ip = you cannot connect to this cs:go server because it is restricted to lan connections only.
login token is valid.
os = windows 10
csgosl = v2.16

how can i set sv_lan to 0 ?

**Comment by lenosisnickerboa** [comment]
I just tried the same thing, disabled lanonly in server tab and it just worked. Just a hint, cmd-start.bat only updates when you press "Start server" so make sure to look into this file only after having changed something and then actually having pressed the "Start server" button (no need to press "Save all settings", that's done automatically when the server is started).

If you still have problems, i.e. the cmd-start.bat file doesn't get updated when you start the server, you can try closing csgosl, edit cmd-start.bat and set sv_lan to 0, save the file and click cmd-start.bat directly. That should start the server directly (but it will not be controlled by csgosl of course). If this works and people can connect from outside your lan then we know it's some internal csgosl issue. Otherwise, if you still have problems, there is something else stopping you from hosting a public server. 

Sounds like you have already read [Hosting a public server](https://github.com/lenosisnickerboa/csgosl/wiki/Host-public-server)?

Please report any  progress back.

**Comment by usgitAz** [comment]
Thanks for the quick support
i edit cmd-start.bat , change sv_lan to 0 and run .
its worked! i see pubic ip in cmd and connect with.
also my friend connected successfully .
but when i start server with csgosl its not working!
in cmd-start.bat port = 27015 but server run on port 27016!

**Comment by usgitAz** [comment]
My problem is solved !
when i change the banprotection , i don't click the allowbannedinpublicservers button 
and this option It was crashing my server settings ! (sv_lan = 0 start server on port 27016)

**Comment by lenosisnickerboa** [comment]
But beware that disabling banprotection on a public server might get you
banned if running certain mods.

**Comment by lenosisnickerboa** [comment]
Thanks for following up and closing issue!
