### ISSUE TITLE
Startmap overridden by workshop collection

### ISSUE THREAD

**Issue by spiral6** [lenosisnickerboa/csgosl#39]
I have a custom workshop id (XXXXXXXX) and startmap id (XXXXXXXXX) inside both of the text boxes. However, although it seems to be listening to hosting the workshop collection, the startmap parameter won't work.

**Comment by lenosisnickerboa** [comment]
I assume you mean you entered workshop ids in the mapgroup and a startmap entries in the Run tab, right?

I tested this and csgosl, as I expected, supplies "+host_workshop_collection 123456789  +host_workshop_startmap 987654321" to the srcds options. What srcds chooses to do with these options are beyond csgosl control, i.e. I can't fix it since this is controlled by the srcds command from Valve. My guess is stating a workshop mapgroup and startmap is not supported. Looking at the examples Valve either shows how to host a collection or a map, never both at the same time. I could be wrong of course, if you find a working example using srcds please send me the link and I'll try it.

A workaround: 
First just enter the workshop collection id in the mapgroup entry and start the server. Let it download all maps. (You can test to connect and start a game on the server to make sure it has finished). Restart csgosl. All collection maps should now be visible in the Maps tab.

Then create a mapgroup of the new maps in the collection (in the Map Groups tab) and select it as mapgroup (in Run tab). Now enter the workshop map id in the startmap and again start the server. Now this map will be downloaded and be selected as startmap. If you restart csgosl this map also will be visible in the Maps tab and can now be selected in the startmap entry on the Run tab.

Please let me know how this works out for you.

**Comment by spiral6** [comment]
This has worked for me on previous versions, unsure why it isn't working for me now. Will test with what you've said.

**Comment by spiral6** [comment]
This is working. I'll just use this option instead.
