### ISSUE TITLE
Server update resetting "Databases.cfg"

### ISSUE THREAD

**Issue by rumourA** [lenosisnickerboa/csgosl#57]
Minor issue but can get tedious,

**Comment by lenosisnickerboa** [comment]
Yes, this is a tricky one to solve since when the sourcemod zip archive is unpacked it will overwrite your databases.cfg with its own default. Sometimes this is a good thing (e.g. if you messed up some cfg file and reinstall to get back to some sane defaults) and in your case a bad thing. Not sure how I would solve this in a good way, perhaps introduce some option "Keep all cfg files in sourcemod during installation" and set it to default "off" and then someone who have fiddled around with some cfg file can set it to "on" to keep the cfg files. Sounds good? Or do you have some other suggestion on how to solve this?

**Comment by rumourA** [comment]
That sounds like the best way to solve it to me.

**Comment by lenosisnickerboa** [comment]
OK, already tagged it enhancement so I'll have a look at it for the next release.

**Comment by lenosisnickerboa** [comment]
Please check out the latest release 1.2.3 which now allows you to preserve your sourcemod config files during update by adding the string CSGOSLDONOTTOUCH somewhere on the first line of the config file.
