### ISSUE TITLE
No clear location for custom cfgs, everything overwritten on Save All

### ISSUE THREAD

**Issue by TeamDman** [lenosisnickerboa/csgosl#58]
Trying to add a custom cfg that acts like a gamemode file, but everything is overwritten when save all settings is pressed

**Comment by lenosisnickerboa** [comment]
Not sure if I understand your problem but it sounds like the same problem described and answered here: https://github.com/lenosisnickerboa/csgosl/issues/56 with the only difference you change the custom gamemode file and Tom100080 changed classic competetive. You're changing stuff in the Custom config tab right?

**Comment by TeamDman** [comment]
I tried using the tab but it is less convenient than being able to edit the files to copy and paste. It also seems that the tabs are missing a few niche cvars such as cash_player_get_killed

**Comment by lenosisnickerboa** [comment]
Yup, it is no longer complete since the last release. But you can add these vars to the gui by adding them to the _server.cfg file.

Also, you may be a more advanced user which prefers editing the files directly. The intended audience for csgosl is people who can't or won't do this and prefer less control as a tradeoff for less control.
