### ISSUE TITLE
Why show"no steam account token was specified...."

### ISSUE THREAD

**Issue by 726581913** [lenosisnickerboa/csgosl#66]
![qq 20170222204908](https://cloud.githubusercontent.com/assets/25955143/23212171/719942f4-f940-11e6-9463-398dbd69c74f.png)
![qq 20170222204823](https://cloud.githubusercontent.com/assets/25955143/23212172/71a79b74-f940-11e6-806b-8f946843080e.png)
is there any problem in my set? thank you very much.

**Comment by rishabhc43** [comment]
That is a bug in csgosl... I have the same issue.
When you start a new  server you can check the console tab in csgosl. There the launch options are shown (they are similar to the .bat file while can be used to launch the server manually).  There is no launch option which is used to specify the steam login token (i.e. +sv_setsteamaccount "YourSteamToken")
That is why it is showing that error. You can manually create a new .bat file and paste the contents of the console + your steam token and you are good to go
![screenshot 32 _li](https://cloud.githubusercontent.com/assets/25932852/23257975/1e9caef4-f9ec-11e6-8add-9d6a38f5f2d7.jpg)

**Comment by lenosisnickerboa** [comment]
The sv_setsteamaccount option is used to set the gameserverlogintoken (GSLT, set on the Steam tab). If you set this option and disable the lanonly option in the Server tab sv_setsteamaccount will be set to your GSLT. See [GSLT](http://dathost.net/blog/how-to-create-and-use-gameserver-login-tokens-gslts-for-your-dedicated-csgo-server/).

On lanonly servers the sv_setsteamaccount is not set at all since it is only used on public servers.

The steamid option on the Steam tab is only used to make you sourcemod admin. A bit unclear indeed...

**Comment by lenosisnickerboa** [comment]
If you feel this answer was incorrect, please reopen the issue again. Closing for now.

**Comment by 726581913** [comment]
1.creat a file named server.cfg in csgo\cfg.write
"sv_setsteamaccount   "token" "

if it doesn't work,see no.2

2.creat a file named runserver.bat in where there is srcds.exe.
write
"srcds.exe -game csgo -console -ip 124.228.91.190 -usercon +game_type 0 +game_mode 0 +port 27015  +map de_dust2 -tickrate 128  -maxplayers_override 32 +mapgroup mg_active"
remember replace IP with your own IP.
then open runserver.bat to start the server.

PS.i am an amateur,you could ask for help for standard solution from blogger.

**Comment by 726581913** [comment]
Important things, do not use Notepad editor, it is best to use professional editing software.
