### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by exxis** [lenosisnickerboa/csgosl#70]
i´ve installed the server, made all the important settings, then clicked on Start server and nothing happens. I had csgosl running before, then after a reset at my server i reinstalled it today and i cant figure out where the problem is.
I´ve also checked the wiki but no indication what i might have missed.

**Comment by CJNiiva** [comment]
Do you have a space in one of the folders its installed on?

Sendt fra min iPhone

Den 5. mar. 2017 kl. 21.47 skrev exxis <notifications@github.com<mailto:notifications@github.com>>:


i´ve installed the server, made all the important settings, then clicked on Start server and nothing happens. I had csgosl running before, then after a reset at my server i reinstalled it today and i cant figure out where the problem is.
I´ve also checked the wiki but no indication what i might have missed.

**Comment by CJNiiva** [comment]
I only know that if you copy the csgosl folder and rename it to lets say "surf server" it wont work, and if its "surf_server" instead it works

Sendt fra min iPhone

Den 5. mar. 2017 kl. 21.47 skrev exxis <notifications@github.com<mailto:notifications@github.com>>:


i´ve installed the server, made all the important settings, then clicked on Start server and nothing happens. I had csgosl running before, then after a reset at my server i reinstalled it today and i cant figure out where the problem is.
I´ve also checked the wiki but no indication what i might have missed.

**Comment by lenosisnickerboa** [comment]
Did you reinstall a complete new server at a new location or to the old
location?

Den 5 mars 2017 21:49 skrev "CJNiiva" <notifications@github.com>:

**Comment by lenosisnickerboa** [comment]
At least on windows I run a test server with spaces in the root folder
name. Could of course be a problem with some mod having a hard time with
spaces. On linux I know of a problem with spaces. So yes, better just skip
spaces to rule out that possibility.

Den 5 mars 2017 21:54 skrev "CJNiiva" <notifications@github.com>:

**Comment by CJNiiva** [comment]
https://www.youtube.com/watch?v=2f_V0cj6g0E shadowplay kinda fucked me over, but well, the point is still there:P

**Comment by lenosisnickerboa** [comment]
Can you send me the command line, didn't catch it from the clip :) This
works for me so it would be interesting to compare your command line to
mine.

**Comment by CJNiiva** [comment]
bin/server-start.bat "G:/Servers/CSGO/Surf server/server/srcds.exe"  -game csgo -console -usercon -condebug  +game_type 0 +game_mode 0  +mapgroup surf  +map surf_fruits  +sv_setsteamaccount xxxxxx -authkey xxxxxx  -maxplayers_override 16  -tickrate 102      +hostname "CJ's Surf Server" -port 27015 +sv_lan 0

**Comment by CJNiiva** [comment]
I just changed the authkey and steamaccount because its public, but this is the one with the space that isnt working

**Comment by CJNiiva** [comment]
![image](https://cloud.githubusercontent.com/assets/19373615/23591445/ec6af672-01f0-11e7-9f9e-70723f583d64.png)
so that space I'm guessing is fucking the command over

**Comment by lenosisnickerboa** [comment]
Thanks. I'll have a look. No time right now tho...

**Comment by exxis** [comment]
ok thanks for the information with the spaces, i will try it right now and hope this is the issue

**Comment by exxis** [comment]
yep it was because of the spaces in a folder name of mine, i would suggest you add this to the Troubleshooting section, for linux i knew it cant handle spaces but windows is new to me. Thanks again

**Comment by lenosisnickerboa** [comment]
I'll add an entry to the troubleshooting page, thanks!
