### ISSUE TITLE
Server autostart

### ISSUE THREAD

**Issue by MrDavid949** [lenosisnickerboa/csgosl#79]
Hi, I want to add csgosl.vbs to my start menu Statup group so it launches when Windows starts, but I also want the CS server to start automatically without me having to click the start server button.  Is there a command line option to do that?  Ms cs server is w/out keyboard and monitor and I just want it to auto start.

thanks
David

**Comment by lenosisnickerboa** [comment]
First of all, thanks for the donation, you're the second person contributing to this project after 12000+ downloads 🥇 

Yes, having csgosl autostart the server when you launch csgosl would be an easy addition. This could be combined with the already available option to auto-update the server when starting csgosl. 

I'm also considering combining it with #28. Not sure what would be best for you? Then you would just start the script instead of actually starting csgosl. The script could optionally do the auto-update thing prior to starting the server.

Another idea I'm playing around with is having csgosl restart the server at a certain time, or interval, and if auto-update is enabled it will try to update the server before starting it again. This way your server would always be up-to-date and not require any manual handling.

**Comment by lenosisnickerboa** [comment]
Server autostart is now supported in release 1.6

**Comment by MrDavid949** [comment]
Wow, I can't believe that. csgosl is great, I wish more would contribute.  Maybe add a $1 or $2 contribute link to the main dialog.  I have not downloaded 1.6 yet.  Will try it tonight.


thanks

David


________________________________
