### ISSUE TITLE
[Need Help] can't get the server into online mode with skin and knife plugins

### ISSUE THREAD

**Issue by IcyTower1337** [lenosisnickerboa/csgosl#84]
Hello,

First of all, I'd like to apologise for making this issue, as it's not an issue, but more of a "pls help" kinda thing...

I'm kinda new to csgo hosting, did a few things back in 1.6 days, no coding tho...

I got my server to boot into lan mode with the "dangerous" plugins, and everything was fine, but i tried making it an online one and it just boots into lan mode anyway even with me putting the gamserver id that i got...

does anyone know if im doing anything wrong? I also tried using hamachi so my friends could join (it'll only be a private server for about 4 people), and when they used the ip, it told them it only allowed people in the same network, which should work because thats what hamachi is for right?

Again I apologise for this thread, but i hope anyone out there could maybe give me a hand in solving this issue.

Thanks,
IcyTower1337

**Comment by CJNiiva** [comment]
Yes, you need a gameserver token or whatever its called, should be in first or second tab maybe the third look for it:) I'm sure you will figure it out

Sendt fra min iPhone

Den 23. apr. 2017 kl. 13.34 skrev IcyTower1337 <notifications@github.com<mailto:notifications@github.com>>:


Hello,

First of all, I'd like to apologise for making this issue, as it's not an issue, but more of a "pls help" kinda thing...

I'm kinda new to csgo hosting, did a few things back in 1.6 days, no coding tho...

I got my server to boot into lan mode with the "dangerous" plugins, and everything was fine, but i tried making it an online one and it just boots into lan mode anyway even with me putting the gamserver id that i got...

does anyone know if im doing anything wrong? I also tried using hamachi so my friends could join (it'll only be a private server for about 4 people), and when they used the ip, it told them it only allowed people in the same network, which should work because thats what hamachi is for right?

Again I apologise for this thread, but i hope anyone out there could maybe give me a hand in solving this issue.

Thanks,
IcyTower1337

**Comment by CJNiiva** [comment]
After that you should be able to have the server online

Sendt fra min iPhone

Den 23. apr. 2017 kl. 13.34 skrev IcyTower1337 <notifications@github.com<mailto:notifications@github.com>>:


Hello,

First of all, I'd like to apologise for making this issue, as it's not an issue, but more of a "pls help" kinda thing...

I'm kinda new to csgo hosting, did a few things back in 1.6 days, no coding tho...

I got my server to boot into lan mode with the "dangerous" plugins, and everything was fine, but i tried making it an online one and it just boots into lan mode anyway even with me putting the gamserver id that i got...

does anyone know if im doing anything wrong? I also tried using hamachi so my friends could join (it'll only be a private server for about 4 people), and when they used the ip, it told them it only allowed people in the same network, which should work because thats what hamachi is for right?

Again I apologise for this thread, but i hope anyone out there could maybe give me a hand in solving this issue.

Thanks,
IcyTower1337

**Comment by IcyTower1337** [comment]
I have done that, but it doesn't work, right after I put the gameserver token where it's supposed to be, I start up the server using csgosl but in the console it says its only in LAN only mode. 
Am I doing something wrong?

**Comment by CJNiiva** [comment]
Try updating

Sendt fra min iPhone

Den 23. apr. 2017 kl. 15.14 skrev IcyTower1337 <notifications@github.com<mailto:notifications@github.com>>:


I have done that, but it doesn't work, right after I put the gameserver token where it's supposed to be, I start up the server using csgosl but in the console it says its only in LAN only mode.
Am I doing something wrong?

**Comment by IcyTower1337** [comment]
****************************************************
*                                                  *
*  No Steam account token was specified.           *
*  Logging into anonymous game server account.     *
*  Connections will be restricted to LAN only.     *
*                                                  *
*  To create a game server account go to           *
*  http://steamcommunity.com/dev/managegameservers *
*                                                  *
****************************************************

Thats what i get even tho i did actually put one where it's supposed to be, got any idea what im doing wrong?

**Comment by CJNiiva** [comment]
Hmm, try making a new key

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by IcyTower1337** [comment]
Tried that, no luck, I made a key for the 740 app which is the srcds, is that correct? or am I doing it wrong?

**Comment by CJNiiva** [comment]
I dunno, is there an option for 730?

Sendt fra min iPhone

Den 23. apr. 2017 kl. 18.15 skrev IcyTower1337 <notifications@github.com<mailto:notifications@github.com>>:


Tried that, no luck, I made a key for the 740 app which is the srcds, is that correct? or am I doing it wrong?

**Comment by lenosisnickerboa** [comment]
Hi,
I suggest you read this page [Help on Sourcemod](https://github.com/lenosisnickerboa/csgosl/wiki/Help-on-Sourcemod) which explains why csgosl does what it does. In short, csgosl will enforce lanonly games, don't set GSLT, ... when you have "bad" sourcemod plugins enabled. csgosl does this to protect you from being permanently banned by Valve. So what you are experiencing is exactly what to be expected.

Regarding Hamachi usage, I never got that working. Instead I setup a VPN using my router. It works fine and I can invite people outside my LAN, they connect via the VPN and are accepted by the csgo server in lanonly mode.

**Comment by IcyTower1337** [comment]
Hey, 
First of all i'd really like to thank you for the really good explanation, I understand now why that happened.

Secondly, if I may ask, would you be kind eneugh to maybe route me somewhere where i can learn how to setup said vpn so my friends can connect?
I really just wanted to play some private matches with my friends using !ws and !knife, no money involved or anything.

Thank you again,
Icy

**Comment by lenosisnickerboa** [comment]
Np, we'll try to fix this. Do you know if your router has VPN support? What
router model do you have?

Den 23 apr. 2017 10:02 em skrev "IcyTower1337" <notifications@github.com>:

**Comment by IcyTower1337** [comment]
Hey sorry i had to check which one it was, it's a Hitron GVE39321/Hitron GVE39320  I'm not 100% sure which one it is, could you maybe check if it's compatible?

**Comment by lenosisnickerboa** [comment]
Browsed the online manual and I can't find anything about VPN support
unfortunately :( Then I guess we're back to Hamachi which I tried and
failed. Maybe there's some Hamachi forum, or try googling something like
"VPN csgo server".

There's also other VPN solutions but this is not something I have tried and
got working.

**Comment by IcyTower1337** [comment]
I tried messing about in the router's page, but I've not found anything vpn related, I've tried looking around hamachi to see if maybe i could get it to work but no luck either (neither public ip nor hamachi's ip worked), is there maybe a workaround to make it to work?

**Comment by lenosisnickerboa** [comment]
Sorry, no one I'm aware of.

Den 24 apr. 2017 4:51 em skrev "IcyTower1337" <notifications@github.com>:

**Comment by CJNiiva** [comment]
Try opening your ports instead😊 its called port forwarding, just google it and your router and it should be relatively easy

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by IcyTower1337** [comment]
I can do that, the problem is that I'm using some "bad" plugins, that valve doesn't want us to use, so if i did an online server, I'd get banned and thats why i can't do it.

**Comment by CJNiiva** [comment]
You can force the server to be online anyways, its a low chance to be banned, and if you do get ban its not a vac ban, you can still play the game

Sendt fra min iPhone

Den 24. apr. 2017 kl. 23.23 skrev IcyTower1337 <notifications@github.com<mailto:notifications@github.com>>:


I can do that, the problem is that I'm using some "bad" plugins, that valve doesn't want us to use, so if i did an online server, I'd get banned and thats why i can't do it.

**Comment by IcyTower1337** [comment]
And how would I do that using csgosl?

**Comment by CJNiiva** [comment]
Turn off the ban protection on the almost bottom of the sourcemod tab

Sendt fra min iPhone

Den 25. apr. 2017 kl. 11.47 skrev IcyTower1337 <notifications@github.com<mailto:notifications@github.com>>:


And how would I do that using csgosl?

**Comment by lenosisnickerboa** [comment]
I would not recommend going online with "bad" plugins but you're free to do it of course...
