### ISSUE TITLE
using master branch build, csgo server won't start

### ISSUE THREAD

**Issue by abshkd** [lenosisnickerboa/csgosl#87]
Hi, 
I cloned your `master` locally. Built it and took the files from `out/` to a new path. I followed the guide and started a public server. The steam server key is set. 
issues

- [x ] steamclient.so cannot be found. I fixed it by searching and copying from `server` directory
- [ ] server still crashes on start. [pastebin](https://pastebin.com/zbsyeNks). Note that I am running the server manually outside of csgosl, but the server was installed by csgosl just to clarify. I thought its best to just try directly but the error is same
- [ ] despite using the `master` branch but not your release `tag` I get the `update available` prompt that I am on version 1.8.2. This could indicate I did something wrong.

Environment: Ubuntu 16.04 LTS 32 Bit

Please let me know if you need any other information. Would love to see this tool work and here to help.

**Comment by lenosisnickerboa** [comment]
I'll have a look later, just a quick question first; did you use the zip
file you built or the separate files in out/? You should only take the
zipped file an unzip it where you want to install csgosl.

On May 13, 2017 21:43, "Abhishek Dujari" <notifications@github.com> wrote:

Hi,
I cloned your master locally. Built it and took the files from out/ to a
new path. I followed the guide and started a public server. The steam
server key is set.
issues

   - [x ] steamclient.so cannot be found. I fixed it by searching and
   copying from server directory
   - server still crashes on start. pastebin <https://pastebin.com/zbsyeNks>.
   Note that I am running the server manually outside of csgosl, but the
   server was installed by csgosl just to clarify. I thought its best to just
   try directly but the error is same
   - despite using the master branch but not your release tag I get the update
   available prompt that I am on version 1.8.2. This could indicate I did
   something wrong.

Environment: Ubuntu 16.04 LTS 32 Bit

Please let me know if you need any other information. Would love to see
this tool work and here to help.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lenosisnickerboa/csgosl/issues/87>, or mute the thread

**Comment by abshkd** [comment]
good point. I believe I copied the files. Let me try it and report back
before you put any more time on this.
thank you for getting back so quickly

**Comment by abshkd** [comment]
I tried with a fresh system and a new build checked out. I still ended up with 1.8.2 However i was able to simply update from your client. Which is awesome. However this does point to an issue with build script. I wish I had more time to look into the sources. But I will try

**Comment by lenosisnickerboa** [comment]
Thanks for pointing this out. I had forgot to push the latest sources, I
just released the binaries. Fixed now, sorry for any inconvenience.

**Comment by abshkd** [comment]
No problem at all, in fact thanks for working on this and sharing it. I
hope to help in anyway I can and would definitely like to see a bit more.
For e.g. an admin page to kick/ban users, add maps etc. It's perfect as an
installer but you need a few more features before you will see some major
support from server admins like myself.

**Comment by lenosisnickerboa** [comment]
Have a look at release 2.0 (coming soon) containing a lot of new config options and rcon access via console or shortcut buttons.
